"""Ghostscript pdfwrite backend for difficult PDF/A repairs.

Ghostscript is an optional external executable. It is deliberately not
bundled with pdf2pdfa; callers are responsible for installing and licensing it
appropriately for their environment.
"""

from __future__ import annotations

from importlib.resources import files
import os
from pathlib import Path
import shutil
import subprocess
import tempfile

from ..icc import read_icc_profile
from .base import BackendResult, BackendUnavailableError, ConversionBackendError


def _ps_escape(value: str) -> str:
    return value.replace("\\", "\\\\").replace("(", "\\(").replace(")", "\\)")


class GhostscriptBackend:
    name = "ghostscript"

    def __init__(self, executable: str | None = None, timeout: int = 300) -> None:
        self.executable = executable or self._discover()
        self.timeout = timeout

    @staticmethod
    def _discover() -> str | None:
        for candidate in ("gs", "gswin64c", "gswin32c"):
            resolved = shutil.which(candidate)
            if resolved:
                return resolved
        return None

    def available(self) -> bool:
        return bool(
            self.executable
            and (shutil.which(self.executable) or Path(self.executable).is_file())
        )

    @staticmethod
    def _definition(profile_path: Path, components: int, identifier: str) -> str:
        profile = _ps_escape(str(profile_path.resolve()))
        ident = _ps_escape(identifier)
        return f"""%!
% Generated by pdf2pdfa. Based on Ghostscript's documented PDFA_def.ps pattern.
/ICCProfile ({profile}) def
[/_objdef {{icc_PDFA}} /type /stream /OBJ pdfmark
[{{icc_PDFA}} << /N {components} >> /PUT pdfmark
[{{icc_PDFA}} ICCProfile (r) file /PUT pdfmark
[/_objdef {{OutputIntent_PDFA}} /type /dict /OBJ pdfmark
[{{OutputIntent_PDFA}} <<
  /Type /OutputIntent
  /S /GTS_PDFA1
  /DestOutputProfile {{icc_PDFA}}
  /RegistryName (http://www.color.org)
  /OutputConditionIdentifier ({ident})
  /Info ({ident})
>> /PUT pdfmark
[{{Catalog}} <</OutputIntents [ {{OutputIntent_PDFA}} ]>> /PUT pdfmark
"""

    def convert(
        self,
        input_path: str | Path,
        output_path: str | Path,
        *,
        level: str,
        icc_profile: str | Path | None = None,
        font_path: str | Path | None = None,
    ) -> BackendResult:
        del font_path  # Ghostscript performs its own font resolution/embedding.
        if not self.available():
            raise BackendUnavailableError(
                "Ghostscript is required for the full-rewrite fallback but no gs/gswin*c executable was found"
            )

        input_path = Path(input_path).resolve()
        output_path = Path(output_path).resolve()
        output_path.parent.mkdir(parents=True, exist_ok=True)
        source_profile = Path(
            str(icc_profile or files("pdf2pdfa").joinpath("data/sRGB.icc.b64"))
        )
        profile = read_icc_profile(source_profile)
        if profile.components not in (3, 4):
            raise ConversionBackendError(
                "Ghostscript PDF/A fallback currently requires an RGB or CMYK OutputIntent profile"
            )
        if profile.components == 4 and not profile.tags.intersection(
            {"B2A0", "B2A1", "B2A2"}
        ):
            raise ConversionBackendError(
                "A CMYK Ghostscript OutputIntent must provide a B2A transform for conversion into the target CMYK space"
            )

        color_strategy = "RGB" if profile.components == 3 else "CMYK"
        part = level[0]
        compatibility = "1.4" if part == "1" else "1.7"

        with tempfile.TemporaryDirectory(prefix="pdf2pdfa-gs-") as tempdir_name:
            tempdir = Path(tempdir_name)
            materialized_icc = tempdir / "output-intent.icc"
            materialized_icc.write_bytes(profile.data)
            definition = tempdir / "PDFA_def.ps"
            definition.write_text(
                self._definition(
                    materialized_icc,
                    profile.components,
                    source_profile.stem,
                ),
                encoding="ascii",
            )
            candidate = tempdir / "candidate.pdf"

            cmd = [
                str(self.executable),
                f"-dPDFA={part}",
                "-dBATCH",
                "-dNOPAUSE",
                "-dSAFER",
                "-dPDFACompatibilityPolicy=1",
                "-sDEVICE=pdfwrite",
                f"-dCompatibilityLevel={compatibility}",
                f"-sColorConversionStrategy={color_strategy}",
                "-dEmbedAllFonts=true",
                "-dSubsetFonts=true",
                "-dCompressFonts=true",
                "-dDetectDuplicateImages=true",
                "-dPreserveAnnots=true",
                f"--permit-file-read={materialized_icc}",
                f"-sOutputFile={candidate}",
                str(definition),
                str(input_path),
            ]
            try:
                completed = subprocess.run(
                    cmd,
                    capture_output=True,
                    text=True,
                    timeout=self.timeout,
                    check=False,
                )
            except subprocess.TimeoutExpired as exc:
                raise ConversionBackendError(
                    f"Ghostscript timed out after {self.timeout}s"
                ) from exc
            except OSError as exc:
                raise BackendUnavailableError(
                    f"Could not execute Ghostscript: {exc}"
                ) from exc

            if (
                completed.returncode != 0
                or not candidate.is_file()
                or candidate.stat().st_size == 0
            ):
                diagnostic = completed.stderr.strip() or completed.stdout.strip()
                raise ConversionBackendError(
                    f"Ghostscript PDF/A conversion failed (exit {completed.returncode}): {diagnostic[-4000:]}"
                )

            os.replace(candidate, output_path)
            return BackendResult(
                backend=self.name,
                output_path=output_path,
                stdout=completed.stdout,
                stderr=completed.stderr,
            )
