#!/usr/bin/env python3
"""Compile Adobe CMap resources into pdf2pdfa's compact owned data format.

This is development/release tooling, never a runtime dependency.  It consumes a
local checkout of Adobe's `cmap-resources` repository and emits deterministic
Python data containing only codespaces, point mappings, ranges, notdef fallback
mappings, WMode and usecmap inheritance.

Example:
    python scripts/compile_cmaps.py \
        /path/to/cmap-resources \
        --name 90ms-RKSJ-H --name 90ms-RKSJ-V \
        --output /tmp/predefined_cmap_data.py
"""

from __future__ import annotations

import argparse
from hashlib import sha256
from pathlib import Path
from pprint import pformat
import sys

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from pdf2pdfa.native.cmap import CIDCMap, CMapError  # noqa: E402


HEADER = '''"""Generated predefined CMap mapping data.

DO NOT EDIT MANUALLY. Generated by scripts/compile_cmaps.py from Adobe CMap
Resources. See THIRD_PARTY_NOTICES.md for provenance and license.
"""

from __future__ import annotations

'''


def _source_index(root: Path) -> dict[str, Path]:
    result: dict[str, Path] = {}
    for path in root.rglob("*"):
        if not path.is_file() or path.name.startswith("."):
            continue
        # Only actual CMap resource folders are intended inputs.  cid2code and
        # prose files are not named predefined CMaps and are ignored unless a
        # caller explicitly asks for a colliding filename.
        if "/CMap/" not in path.as_posix():
            continue
        if path.name in result and result[path.name] != path:
            raise SystemExit(
                f"duplicate CMap resource name {path.name!r}: "
                f"{result[path.name]} and {path}"
            )
        result[path.name] = path
    return result


def _point_rows(values: dict[bytes, int]) -> tuple[tuple[int, int, int], ...]:
    return tuple(
        sorted(
            (int.from_bytes(raw, "big"), len(raw), int(cid))
            for raw, cid in values.items()
        )
    )


def _compile_one(
    name: str,
    *,
    index: dict[str, Path],
    cache: dict[str, CIDCMap],
    source_hashes: dict[str, str],
    active: set[str],
) -> CIDCMap:
    if name in cache:
        return cache[name]
    if name in active:
        raise CMapError(f"source CMap inheritance cycle at /{name}")
    path = index.get(name)
    if path is None:
        raise CMapError(f"source tree contains no CMap named /{name}")
    active.add(name)
    try:
        payload = path.read_bytes()
        source_hashes[name] = sha256(payload).hexdigest()

        def registry(base_name: str) -> CIDCMap:
            return _compile_one(
                base_name,
                index=index,
                cache=cache,
                source_hashes=source_hashes,
                active=active,
            )

        cmap = CIDCMap.parse(payload, registry=registry, name=name)
        cache[name] = cmap
        return cmap
    finally:
        active.remove(name)


def _serialize(cmap: CIDCMap) -> dict[str, object]:
    return {
        "vertical": bool(cmap.vertical),
        "base": cmap.base.name if cmap.base is not None else None,
        "codespaces": tuple(
            (item.low, item.high, item.length) for item in cmap.local_codespaces
        ),
        "cid_chars": _point_rows(cmap.cid_chars),
        "cid_ranges": tuple(
            (item.start, item.end, item.code_length, item.cid_start)
            for item in cmap.cid_ranges
        ),
        "notdef_chars": _point_rows(cmap.notdef_chars),
        "notdef_ranges": tuple(
            (item.start, item.end, item.code_length, item.cid)
            for item in cmap.notdef_ranges
        ),
    }


def compile_resources(source_root: Path, names: list[str]) -> tuple[dict[str, dict[str, object]], dict[str, str]]:
    index = _source_index(source_root)
    cache: dict[str, CIDCMap] = {}
    hashes: dict[str, str] = {}
    for name in names:
        _compile_one(name, index=index, cache=cache, source_hashes=hashes, active=set())

    # Emit requested resources plus their inherited bases in deterministic name
    # order.  This makes an output module self-contained.
    selected: set[str] = set()
    for name in names:
        current = cache[name]
        while current is not None:
            selected.add(current.name)
            current = current.base
    data = {name: _serialize(cache[name]) for name in sorted(selected)}
    return data, {name: hashes[name] for name in sorted(selected)}


def render_module(data: dict[str, dict[str, object]], hashes: dict[str, str]) -> str:
    return (
        HEADER
        + "SOURCE_SHA256 = "
        + pformat(hashes, sort_dicts=True, width=100)
        + "\n\nCMAP_DATA = "
        + pformat(data, sort_dicts=True, width=120)
        + "\n"
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("source_root", type=Path)
    parser.add_argument("--name", action="append", required=True, dest="names")
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args(argv)

    data, hashes = compile_resources(args.source_root.resolve(), args.names)
    output = render_module(data, hashes)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(output, encoding="utf-8", newline="\n")
    print(f"compiled {len(data)} CMap resources -> {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
