"""ICC profiles generated by the owned color engine.

No opaque ICC file is required by the native runtime.  sRGB is represented as a
matrix/TRC ICC v2 profile generated from the sRGB transfer function and D50-
adapted primaries.  The fallback CMYK profile is a deterministic LUT profile
whose model is explicitly defined in this source file; it is not intended to
impersonate a particular printing condition.
"""

from __future__ import annotations

import struct


_D50 = (0.9642, 1.0, 0.8249)
_SRGB_R = (0.4360747, 0.2225045, 0.0139322)
_SRGB_G = (0.3850649, 0.7168786, 0.0971045)
_SRGB_B = (0.1430804, 0.0606169, 0.7141733)

# Inverse of the D50-adapted sRGB-to-XYZ matrix above.
_XYZ_TO_RGB = (
    (3.1338561, -1.6168667, -0.4906146),
    (-0.9787684, 1.9161415, 0.0334540),
    (0.0719453, -0.2289914, 1.4052427),
)


def _clamp01(value: float) -> float:
    return max(0.0, min(1.0, value))


def _s15fixed16(value: float) -> bytes:
    scaled = int(round(value * 65536.0))
    return int(scaled).to_bytes(4, "big", signed=True)


def _pad4(data: bytes) -> bytes:
    return data + b"\x00" * ((-len(data)) % 4)


def _xyz_tag(xyz: tuple[float, float, float]) -> bytes:
    return b"XYZ " + b"\x00" * 4 + b"".join(_s15fixed16(value) for value in xyz)


def _text_tag(text: str) -> bytes:
    raw = text.encode("ascii", "replace")
    return b"text" + b"\x00" * 4 + raw + b"\x00"


def _desc_tag(text: str) -> bytes:
    raw = text.encode("ascii", "replace") + b"\x00"
    return (
        b"desc"
        + b"\x00" * 4
        + len(raw).to_bytes(4, "big")
        + raw
        + (0).to_bytes(4, "big")
        + (0).to_bytes(4, "big")
        + (0).to_bytes(2, "big")
        + bytes(67)
    )


def _srgb_linear(encoded: float) -> float:
    encoded = _clamp01(encoded)
    if encoded <= 0.04045:
        return encoded / 12.92
    return ((encoded + 0.055) / 1.055) ** 2.4


def _srgb_encode(linear: float) -> float:
    linear = _clamp01(linear)
    if linear <= 0.0031308:
        return 12.92 * linear
    return 1.055 * (linear ** (1.0 / 2.4)) - 0.055


def _rgb_to_xyz(rgb: tuple[float, float, float]) -> tuple[float, float, float]:
    r, g, b = (_srgb_linear(value) for value in rgb)
    return (
        _SRGB_R[0] * r + _SRGB_G[0] * g + _SRGB_B[0] * b,
        _SRGB_R[1] * r + _SRGB_G[1] * g + _SRGB_B[1] * b,
        _SRGB_R[2] * r + _SRGB_G[2] * g + _SRGB_B[2] * b,
    )


def _xyz_to_rgb(xyz: tuple[float, float, float]) -> tuple[float, float, float]:
    x, y, z = xyz
    linear = tuple(
        row[0] * x + row[1] * y + row[2] * z for row in _XYZ_TO_RGB
    )
    return tuple(_clamp01(_srgb_encode(value)) for value in linear)  # type: ignore[return-value]


def _cmyk_to_rgb(cmyk: tuple[float, float, float, float]) -> tuple[float, float, float]:
    c, m, y, k = (_clamp01(value) for value in cmyk)
    return (
        (1.0 - c) * (1.0 - k),
        (1.0 - m) * (1.0 - k),
        (1.0 - y) * (1.0 - k),
    )


def _rgb_to_cmyk(rgb: tuple[float, float, float]) -> tuple[float, float, float, float]:
    r, g, b = (_clamp01(value) for value in rgb)
    k = 1.0 - max(r, g, b)
    if k >= 1.0 - 1e-12:
        return (0.0, 0.0, 0.0, 1.0)
    denominator = 1.0 - k
    return (
        _clamp01((1.0 - r - k) / denominator),
        _clamp01((1.0 - g - k) / denominator),
        _clamp01((1.0 - b - k) / denominator),
        _clamp01(k),
    )


def _curve_tag(samples: int = 1024) -> bytes:
    if samples < 2 or samples > 65535:
        raise ValueError("ICC curve sample count must be in [2, 65535]")
    values = []
    for index in range(samples):
        encoded = index / (samples - 1)
        linear = _srgb_linear(encoded)
        values.append(int(round(_clamp01(linear) * 65535.0)))
    return (
        b"curv"
        + b"\x00" * 4
        + samples.to_bytes(4, "big")
        + b"".join(value.to_bytes(2, "big") for value in values)
    )


def _lut8_tag(
    *,
    input_channels: int,
    output_channels: int,
    grid_points: int,
    transform,
) -> bytes:
    if not 2 <= grid_points <= 255:
        raise ValueError("lut8 grid points must be in [2, 255]")
    if not 1 <= input_channels <= 15 or not 1 <= output_channels <= 15:
        raise ValueError("ICC LUT channel count out of range")
    header = bytearray(b"mft1" + b"\x00" * 4)
    header.extend(bytes([input_channels, output_channels, grid_points, 0]))
    # Identity 3x3 matrix. For non-three-channel inputs the matrix is ignored.
    for row in range(3):
        for column in range(3):
            header.extend(_s15fixed16(1.0 if row == column else 0.0))

    input_tables = bytearray()
    for _ in range(input_channels):
        input_tables.extend(range(256))

    clut = bytearray()
    total = grid_points ** input_channels
    for index in range(total):
        remainder = index
        coordinates = [0] * input_channels
        for axis in range(input_channels - 1, -1, -1):
            coordinates[axis] = remainder % grid_points
            remainder //= grid_points
        normalized = tuple(value / (grid_points - 1) for value in coordinates)
        values = transform(normalized)
        if len(values) != output_channels:
            raise ValueError("ICC LUT transform returned the wrong channel count")
        clut.extend(int(round(_clamp01(value) * 255.0)) for value in values)

    output_tables = bytearray()
    for _ in range(output_channels):
        output_tables.extend(range(256))
    return bytes(header + input_tables + clut + output_tables)


def _a2b_cmyk(values: tuple[float, ...]) -> tuple[float, float, float]:
    rgb = _cmyk_to_rgb((values[0], values[1], values[2], values[3]))
    return tuple(_clamp01(value) for value in _rgb_to_xyz(rgb))  # type: ignore[return-value]


def _b2a_cmyk(values: tuple[float, ...]) -> tuple[float, float, float, float]:
    rgb = _xyz_to_rgb((values[0], values[1], values[2]))
    return _rgb_to_cmyk(rgb)


def _profile(
    *,
    profile_class: bytes,
    color_space: bytes,
    tags: list[tuple[bytes, bytes]],
    rendering_intent: int = 1,
) -> bytes:
    header_size = 128
    table_size = 4 + len(tags) * 12
    data_offset = header_size + table_size
    payload = bytearray()
    entries = bytearray()
    offset = data_offset
    for signature, raw in tags:
        raw = _pad4(raw)
        entries.extend(signature)
        entries.extend(offset.to_bytes(4, "big"))
        entries.extend(len(raw).to_bytes(4, "big"))
        payload.extend(raw)
        offset += len(raw)

    total_size = header_size + table_size + len(payload)
    header = bytearray(128)
    header[0:4] = total_size.to_bytes(4, "big")
    header[4:8] = b"py2a"
    header[8:12] = bytes([2, 0x40, 0, 0])
    header[12:16] = profile_class
    header[16:20] = color_space
    header[20:24] = b"XYZ "
    header[24:36] = struct.pack(">6H", 2000, 1, 1, 0, 0, 0)
    header[36:40] = b"acsp"
    header[40:44] = b"pyth"
    header[44:48] = (0).to_bytes(4, "big")
    header[48:52] = b"none"
    header[52:56] = b"none"
    header[56:64] = b"\x00" * 8
    header[64:68] = int(rendering_intent).to_bytes(4, "big")
    header[68:80] = b"".join(_s15fixed16(value) for value in _D50)
    header[80:84] = b"py2a"
    return bytes(header) + len(tags).to_bytes(4, "big") + bytes(entries) + bytes(payload)


def srgb_profile_bytes() -> bytes:
    """Return the deterministic matrix/TRC ICC v2 sRGB display profile."""
    return _profile(
        profile_class=b"mntr",
        color_space=b"RGB ",
        tags=[
            (b"desc", _desc_tag("pdf2pdfa sRGB")),
            (b"cprt", _text_tag("Generated by pdf2pdfa from the sRGB specification")),
            (b"wtpt", _xyz_tag(_D50)),
            (b"rXYZ", _xyz_tag(_SRGB_R)),
            (b"gXYZ", _xyz_tag(_SRGB_G)),
            (b"bXYZ", _xyz_tag(_SRGB_B)),
            (b"rTRC", _curve_tag()),
            (b"gTRC", _curve_tag()),
            (b"bTRC", _curve_tag()),
        ],
    )


def generic_cmyk_profile_bytes(*, grid_points: int = 9) -> bytes:
    """Return the owned deterministic fallback CMYK output profile.

    The model is deliberately explicit: CMYK is converted to RGB using
    ``RGB=(1-C/M/Y)*(1-K)``, then through the sRGB transfer/matrix into D50 XYZ.
    The inverse LUT converts XYZ through inverse sRGB and a conventional
    under-color-removal formula.  This is a reproducible fallback, not a claim
    to characterize a real press or paper condition.
    """
    return _profile(
        profile_class=b"prtr",
        color_space=b"CMYK",
        tags=[
            (b"desc", _desc_tag("pdf2pdfa generic CMYK")),
            (
                b"cprt",
                _text_tag(
                    "Generated by pdf2pdfa; deterministic synthetic CMYK characterization"
                ),
            ),
            (b"wtpt", _xyz_tag(_D50)),
            (
                b"A2B0",
                _lut8_tag(
                    input_channels=4,
                    output_channels=3,
                    grid_points=grid_points,
                    transform=_a2b_cmyk,
                ),
            ),
            (
                b"B2A0",
                _lut8_tag(
                    input_channels=3,
                    output_channels=4,
                    grid_points=max(9, grid_points),
                    transform=_b2a_cmyk,
                ),
            ),
        ],
    )
