"""ICC profiles generated by the owned color engine.

The native engine does not bundle an opaque third-party sRGB profile.  Instead
it serializes a deterministic ICC v2 matrix/TRC display profile from the sRGB
transfer function and the standard D50-adapted sRGB primaries.
"""

from __future__ import annotations

import math
import struct


_D50 = (0.9642, 1.0, 0.8249)
_SRGB_R = (0.4360747, 0.2225045, 0.0139322)
_SRGB_G = (0.3850649, 0.7168786, 0.0971045)
_SRGB_B = (0.1430804, 0.0606169, 0.7141733)


def _s15fixed16(value: float) -> bytes:
    scaled = int(round(value * 65536.0))
    return int(scaled).to_bytes(4, "big", signed=True)


def _u16fixed16(value: float) -> bytes:
    scaled = int(round(value * 65536.0))
    return int(max(0, scaled)).to_bytes(4, "big", signed=False)


def _pad4(data: bytes) -> bytes:
    return data + b"\x00" * ((-len(data)) % 4)


def _xyz_tag(xyz: tuple[float, float, float]) -> bytes:
    return b"XYZ " + b"\x00" * 4 + b"".join(_s15fixed16(value) for value in xyz)


def _text_tag(text: str) -> bytes:
    raw = text.encode("ascii", "replace")
    return b"text" + b"\x00" * 4 + raw + b"\x00"


def _desc_tag(text: str) -> bytes:
    raw = text.encode("ascii", "replace") + b"\x00"
    # ICC v2 'desc' type: ASCII count/string followed by empty Unicode and
    # ScriptCode representations.
    return (
        b"desc"
        + b"\x00" * 4
        + len(raw).to_bytes(4, "big")
        + raw
        + (0).to_bytes(4, "big")
        + (0).to_bytes(4, "big")
        + (0).to_bytes(2, "big")
        + bytes(67)
    )


def _srgb_linear(encoded: float) -> float:
    if encoded <= 0.04045:
        return encoded / 12.92
    return ((encoded + 0.055) / 1.055) ** 2.4


def _curve_tag(samples: int = 1024) -> bytes:
    if samples < 2 or samples > 65535:
        raise ValueError("ICC curve sample count must be in [2, 65535]")
    values = []
    for index in range(samples):
        encoded = index / (samples - 1)
        linear = _srgb_linear(encoded)
        values.append(int(round(max(0.0, min(1.0, linear)) * 65535.0)))
    return (
        b"curv"
        + b"\x00" * 4
        + samples.to_bytes(4, "big")
        + b"".join(value.to_bytes(2, "big") for value in values)
    )


def srgb_profile_bytes() -> bytes:
    """Return a deterministic ICC v2 sRGB display profile owned by pdf2pdfa."""
    tags: list[tuple[bytes, bytes]] = [
        (b"desc", _desc_tag("pdf2pdfa sRGB")),
        (b"cprt", _text_tag("Generated by pdf2pdfa from the sRGB specification")),
        (b"wtpt", _xyz_tag(_D50)),
        (b"rXYZ", _xyz_tag(_SRGB_R)),
        (b"gXYZ", _xyz_tag(_SRGB_G)),
        (b"bXYZ", _xyz_tag(_SRGB_B)),
        (b"rTRC", _curve_tag()),
        (b"gTRC", _curve_tag()),
        (b"bTRC", _curve_tag()),
    ]

    header_size = 128
    table_size = 4 + len(tags) * 12
    data_offset = header_size + table_size
    payload = bytearray()
    entries = bytearray()
    offset = data_offset
    # Identical TRC payloads may legally share storage; keeping each tag
    # independent makes the generated file simpler to audit and deterministic.
    for signature, raw in tags:
        raw = _pad4(raw)
        entries.extend(signature)
        entries.extend(offset.to_bytes(4, "big"))
        entries.extend(len(raw).to_bytes(4, "big"))
        payload.extend(raw)
        offset += len(raw)

    total_size = header_size + table_size + len(payload)
    header = bytearray(128)
    header[0:4] = total_size.to_bytes(4, "big")
    header[4:8] = b"py2a"  # owned CMM signature
    header[8:12] = bytes([2, 0x40, 0, 0])  # ICC version 2.4
    header[12:16] = b"mntr"
    header[16:20] = b"RGB "
    header[20:24] = b"XYZ "
    # Stable profile creation timestamp: 2000-01-01 00:00:00 UTC.
    header[24:36] = struct.pack(">6H", 2000, 1, 1, 0, 0, 0)
    header[36:40] = b"acsp"
    header[40:44] = b"pyth"
    header[44:48] = (0).to_bytes(4, "big")
    header[48:52] = b"none"
    header[52:56] = b"none"
    header[56:64] = b"\x00" * 8
    header[64:68] = (1).to_bytes(4, "big")  # relative colorimetric
    header[68:80] = b"".join(_s15fixed16(value) for value in _D50)
    header[80:84] = b"py2a"

    return bytes(header) + len(tags).to_bytes(4, "big") + bytes(entries) + bytes(payload)
